import React from "react";
import type { Stage1Output, AuditResult } from "../types";

interface Stage1ResultsProps {
  data: Stage1Output;
}

export default function Stage1Results({ data }: Stage1ResultsProps) {
  return (
    <div>
      <div className="mb-4">
        <h2 className="text-lg font-bold text-gray-900 mb-1">Stage 1: Generated Specifications</h2>
        <p className="text-gray-600 text-sm">Product specifications generated by the system</p>
      </div>

      {/* Audit Results Section - Agar audit results available hain */}
      {data.audit && data.audit.length > 0 && (
        <div className="mb-8 bg-gradient-to-r from-blue-50 to-indigo-50 border-l-4 border-blue-500 p-6 rounded-lg">
          <h3 className="text-lg font-bold text-blue-900 mb-4 flex items-center gap-2">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            Audit Results ({data.audit.filter(a => a.status === 'correct').length} Correct, {data.audit.filter(a => a.status === 'incorrect').length} Incorrect)
          </h3>
          
          <div className="space-y-4">
            {data.audit.map((auditItem: AuditResult, index) => (
              <div 
                key={index} 
                className={`p-4 rounded-lg border ${auditItem.status === 'correct' ? 'bg-green-50 border-green-200' : 'bg-red-50 border-red-200'}`}
              >
                <div className="flex items-start justify-between mb-2">
                  <div className="flex items-center gap-2">
                    <div className={`w-6 h-6 rounded-full flex items-center justify-center ${auditItem.status === 'correct' ? 'bg-green-500' : 'bg-red-500'}`}>
                      <span className="text-white text-xs">
                        {auditItem.status === 'correct' ? '✓' : '✗'}
                      </span>
                    </div>
                    <span className="font-semibold text-gray-900">{auditItem.specification}</span>
                  </div>
                  <span className={`text-xs font-medium px-2 py-1 rounded ${auditItem.status === 'correct' ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
                    {auditItem.status.toUpperCase()}
                  </span>
                </div>
                
                {auditItem.status === 'incorrect' && auditItem.explanation && (
                  <div className="mt-2">
                    <p className="text-sm text-gray-700 mb-1">
                      <span className="font-medium">Issue:</span> {auditItem.explanation}
                    </p>
                    {auditItem.problematic_options && auditItem.problematic_options.length > 0 && (
                      <div className="mt-2">
                        <p className="text-xs font-medium text-gray-600 mb-1">Problematic Options:</p>
                        <div className="flex flex-wrap gap-1">
                          {auditItem.problematic_options.map((option, optIndex) => (
                            <span key={optIndex} className="px-2 py-1 bg-red-100 text-red-800 rounded text-xs">
                              {option}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Original Specifications Display */}
      <div className="space-y-6">
        {data.seller_specs.map((spec, specsIdx) => (
          <div key={specsIdx}>
            {/* Header */}
            <div className="mb-3">
              <h3 className="text-md font-bold text-gray-900">
                {spec.pmcat_name || `PMCAT ${specsIdx + 1}`}
              </h3>
              {spec.pmcat_id && (
                <p className="text-gray-500 text-xs">ID: {spec.pmcat_id}</p>
              )}
            </div>

            {spec.mcats.map((mcat, mcatIdx) => (
              <div key={mcatIdx} className="mb-4 border-l border-blue-300 pl-3">
                <h4 className="font-bold text-gray-900 mb-3 text-sm">
                  {mcat.category_name}
                </h4>

                {/* Primary Specs */}
                {mcat.finalized_specs.finalized_primary_specs.specs.length > 0 && (
                  <div className="mb-3">
                    <h5 className="text-xs font-semibold text-blue-700 mb-2 uppercase tracking-wide">Primary</h5>
                    <div className="space-y-2">
                      {mcat.finalized_specs.finalized_primary_specs.specs.map((specItem, sIdx) => (
                        <div key={sIdx} className="bg-blue-50 p-2 rounded border border-blue-200">
                          <div className="font-medium text-gray-900 mb-1 text-sm">
                            {specItem.spec_name}
                          </div>
                          <div className="flex flex-wrap gap-1">
                            {specItem.options.map((option, oIdx) => (
                              <span 
                                key={oIdx} 
                                className="px-2 py-0.5 rounded text-xs bg-blue-100 text-blue-800"
                              >
                                {option}
                              </span>
                            ))}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Secondary Specs */}
                {mcat.finalized_specs.finalized_secondary_specs.specs.length > 0 && (
                  <div className="mb-3">
                    <h5 className="text-xs font-semibold text-green-700 mb-2 uppercase tracking-wide">Secondary</h5>
                    <div className="space-y-2">
                      {mcat.finalized_specs.finalized_secondary_specs.specs.map((specItem, sIdx) => (
                        <div key={sIdx} className="bg-green-50 p-2 rounded border border-green-200">
                          <div className="font-medium text-gray-900 mb-1 text-sm">
                            {specItem.spec_name}
                          </div>
                          <div className="flex flex-wrap gap-1">
                            {specItem.options.map((option, oIdx) => (
                              <span 
                                key={oIdx} 
                                className="px-2 py-0.5 rounded text-xs bg-green-100 text-green-800"
                              >
                                {option}
                              </span>
                            ))}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Tertiary Specs */}
                {mcat.finalized_specs.finalized_tertiary_specs.specs.length > 0 && (
                  <div className="mb-3">
                    <h5 className="text-xs font-semibold text-amber-700 mb-2 uppercase tracking-wide">Tertiary</h5>
                    <div className="space-y-2">
                      {mcat.finalized_specs.finalized_tertiary_specs.specs.map((specItem, sIdx) => (
                        <div key={sIdx} className="bg-amber-50 p-2 rounded border border-amber-200">
                          <div className="font-medium text-gray-900 mb-1 text-sm">
                            {specItem.spec_name}
                          </div>
                          <div className="flex flex-wrap gap-1">
                            {specItem.options.map((option, oIdx) => (
                              <span 
                                key={oIdx} 
                                className="px-2 py-0.5 rounded text-xs bg-amber-100 text-amber-800"
                              >
                                {option}
                              </span>
                            ))}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>
        ))}
      </div>
    </div>
  );
}