import React from "react";
import type { Stage1Output } from "../types";

interface Stage1ResultsProps {
  data: Stage1Output;
}

export default function Stage1Results({ data }: Stage1ResultsProps) {
  return (
    <div>
      <div className="mb-4">
        <h2 className="text-lg font-bold text-gray-900 mb-1">Stage 1: Generated Specifications</h2>
        <p className="text-gray-600 text-sm">Product specifications generated by the system</p>
      </div>

      <div className="space-y-6">
        {data.seller_specs.map((spec, specsIdx) => (
          <div key={specsIdx}>
            {/* Header */}
            <div className="mb-3">
              <h3 className="text-md font-bold text-gray-900">
                {spec.pmcat_name || `PMCAT ${specsIdx + 1}`}
              </h3>
              {spec.pmcat_id && (
                <p className="text-gray-500 text-xs">ID: {spec.pmcat_id}</p>
              )}
            </div>

            {spec.mcats.map((mcat, mcatIdx) => (
              <div key={mcatIdx} className="mb-4 border-l border-blue-300 pl-3">
                <h4 className="font-bold text-gray-900 mb-3 text-sm">
                  {mcat.category_name}
                </h4>

                {/* Primary Specs */}
                {mcat.finalized_specs.finalized_primary_specs.specs.length > 0 && (
                  <div className="mb-3">
                    <h5 className="text-xs font-semibold text-blue-700 mb-2 uppercase tracking-wide">Primary</h5>
                    <div className="space-y-2">
                      {mcat.finalized_specs.finalized_primary_specs.specs.map((specItem, sIdx) => (
                        <div key={sIdx} className="bg-blue-50 p-2 rounded border border-blue-200">
                          <div className="font-medium text-gray-900 mb-1 text-sm">
                            {specItem.spec_name}
                          </div>
                          <div className="flex flex-wrap gap-1">
                            {specItem.options.map((option, oIdx) => (
                              <span 
                                key={oIdx} 
                                className="px-2 py-0.5 rounded text-xs bg-blue-100 text-blue-800"
                              >
                                {option}
                              </span>
                            ))}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Secondary Specs */}
                {mcat.finalized_specs.finalized_secondary_specs.specs.length > 0 && (
                  <div className="mb-3">
                    <h5 className="text-xs font-semibold text-green-700 mb-2 uppercase tracking-wide">Secondary</h5>
                    <div className="space-y-2">
                      {mcat.finalized_specs.finalized_secondary_specs.specs.map((specItem, sIdx) => (
                        <div key={sIdx} className="bg-green-50 p-2 rounded border border-green-200">
                          <div className="font-medium text-gray-900 mb-1 text-sm">
                            {specItem.spec_name}
                          </div>
                          <div className="flex flex-wrap gap-1">
                            {specItem.options.map((option, oIdx) => (
                              <span 
                                key={oIdx} 
                                className="px-2 py-0.5 rounded text-xs bg-green-100 text-green-800"
                              >
                                {option}
                              </span>
                            ))}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Tertiary Specs */}
                {mcat.finalized_specs.finalized_tertiary_specs.specs.length > 0 && (
                  <div className="mb-3">
                    <h5 className="text-xs font-semibold text-amber-700 mb-2 uppercase tracking-wide">Tertiary</h5>
                    <div className="space-y-2">
                      {mcat.finalized_specs.finalized_tertiary_specs.specs.map((specItem, sIdx) => (
                        <div key={sIdx} className="bg-amber-50 p-2 rounded border border-amber-200">
                          <div className="font-medium text-gray-900 mb-1 text-sm">
                            {specItem.spec_name}
                          </div>
                          <div className="flex flex-wrap gap-1">
                            {specItem.options.map((option, oIdx) => (
                              <span 
                                key={oIdx} 
                                className="px-2 py-0.5 rounded text-xs bg-amber-100 text-amber-800"
                              >
                                {option}
                              </span>
                            ))}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>
        ))}
      </div>
    </div>
  );
}